openapi: 3.1.0
info:
  version: 1.0.0
  title: Money guard app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: 
    This is a documentation of students app
tags:
  - name: Auth
    description: Auth operations.
servers:
  - url: http://127.0.0.1:3000
  - url: https://server-money-guard-teamproject.onrender.com
paths:
  /auth/register:
    post:
      $ref: '../swagger/path/auth/register/post.yaml'

  /auth/login:
    post:
      $ref: '../swagger/path/auth/login/post.yaml'

  /auth/logout:
    post:
      $ref: '../swagger/path/auth/logout/post.yaml'

  /transactions:
    get:
      $ref: ../swagger/path/transactions/get.yaml
    post:
      $ref: ../swagger/path/transactions/post.yaml
  
  /transactions/{id}: 
    get: 
      $ref: ../swagger/path/transactions/{id}/get.yaml
    patch: 
      $ref: ../swagger/path/transactions/{id}/patch.yaml
    delete: 
      $ref: ../swagger/path/transactions/{id}/delete.yaml
  
  /summary:
    get:
      $ref: ../swagger/path/summary/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
